GET http://localhost:5000/courses/100/rain HTTP/1.1

###
GET http://localhost:5000/student/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjVhM2Y5ZTI5MzcyNjAwNDM3ZTU0NzkiLCJlbWFpbCI6InlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzE4Mzc1MzA1LCJleHAiOjE3MTg0NjE3MDV9.d3y_LlgewSwz_nCLZuBcfgWOb4TDuIaRBeZTZ9AU1m4


###

POST http://localhost:5000/login/courseadvisor HTTP/1.1
content-type: application/json

{
    "email": "aeworks@gmail.com",
    "password":"1234567890"
}

###
POST https://academify-f0qd.onrender.com/register/student HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "yo@example.com",
  "password": "password123",
  "reg": "20230001",
  "advisor": "6639a71366675a0044a8a287"
}


###
GET https://academify-f0qd.onrender.com/advisors/get-all HTTP/1.1

###
POST  http://localhost:5000/register/parent HTTP/1.1
content-type: application/json

{
    "firstName": "grant",
    "lastName": "eke",
    "email": "ekegrant@gmail.com",
    "password": "1234567890"
}
###
POST  http://localhost:5000/register/student HTTP/1.1
content-type: application/json

{
    "firstName": "grant",
    "lastName": "eke",
    "email": "ekegrant@gmail.com",
    "password": "1234567890",

}

### 
POST http://localhost:5000/login/parent HTTP/1.1
content-type: application/json

{
    "email": "ekegrant@gmail.com",
    "password":"1234567890"
}

###
POST  http://localhost:5000/login/student HTTP/1.1
content-type: application/json

{
      "email": "yo@example.com",
  "password": "password123"
}


###
GET http://localhost:5000/parent/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxNzk1OTE0MCwiZXhwIjoxNzE3OTYyNzQwfQ.JWzuSHT-43sHZbb_OcjrWoVXz3Fe4Ffwe4membfSmFk

###
POST  http://localhost:5000/parent/editProfile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxNjA1NDEzOSwiZXhwIjoxNzE2MDU3NzM5fQ.jN9Da7hM2DTbywbTPoEiK0mTytXISK3w-R20MxXD5ZY

{
    "firstName": "grant",
    "lastName": "eke",
    "password": "1234567890"
}
###
POST  http://localhost:5000/parent/addChild HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxODM2MzA0MiwiZXhwIjoxNzE4MzY2NjQyfQ.0iPzWpQCAcKuJuJIc-dc3jjm1f4qo9T_uXqj3jYQIB0

{
    "regNo": 2019111111
}

###
POST  http://localhost:5000/advisors/semesters HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxODM2MzA0MiwiZXhwIjoxNzE4MzY2NjQyfQ.0iPzWpQCAcKuJuJIc-dc3jjm1f4qo9T_uXqj3jYQIB0

{
    "regNo": 2019111111
}





