@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjVhM2Y5ZTI5MzcyNjAwNDM3ZTU0NzkiLCJlbWFpbCI6InlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzE4Mzc2NDMxLCJleHAiOjE3MTg0NjI4MzF9.EdkBssj6pVbM4B5KI580hoaZlrgG8CHsNwOsEQ6nzwk
@localurl = http://localhost:5000
@prodUrl = https://academify-f0qd.onrender.com

###
POST {{localurl}}/register/student HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "John",
  "email": "johnjohn@example.com",
  "password": "password123",
  "reg": "201912345",
  "advisor": "6639a71366675a0044a8a287"
}

###
POST  {{localurl}}/register/parent HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "John",
    "email": "johnparent@example.com",
    "password": "1234567890"
}

###
POST  {{localurl}}/register/courseadvisor HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "John",
    "email": "johnadvisor@example.com",
    "password": "1234567890"
}

###
POST {{localurl}}/login/student HTTP/1.1
content-type: application/json

{
    "email": "johnjohn@example.com",
    "password":"password123"
}
###
POST {{localurl}}/login/parent HTTP/1.1
content-type: application/json

{
    "email": "johnparent@example.com",
    "password":"1234567890"
}
###
POST {{localurl}}/login/courseadvisor HTTP/1.1
content-type: application/json

{
    "email": "johnadvisor@example.com",
    "password":"1234567890"
}

###
GET {{localurl}}/student/profile HTTP/1.1
Authorization: Bearer {{studentToken}}

###
GET {{localurl}}/student/result HTTP/1.1
Authorization: Bearer {{studentToken}}

###
POST {{localurl}}/course/register HTTP/1.1
Content-Type: application/json

{
  "reg": "201912345",
  "session": "2023/2024",
  "level": "500",
  "semester": "harmattan",
  "courseCodes": ["CSC 507", "CSC 511","CSC 505"]
}

###
GET {{localurl}}/courses/100/rain HTTP/1.1

###
POST {{localurl}}/api/messages/student/:studentId HTTP/1.1
Content-Type: application/json

{
  "content":"testing the microphone again",
  "sender":"662220425f77b2345cf543c6"
}

###
POST {{localurl}}/api/messages/student/advisor/:studentId HTTP/1.1
Content-Type: application/json

{
  "reg": "201912345",
  "session": "2023/2024",
  "level": "500",
  "semester": "harmattan",
  "courseCodes": ["CSC 507", "CSC 511","CSC 505"]
}


###
GET {{localurl}}/api/messages/student/:studentId HTTP/1.1
Content-Type: application/json

{
  "reg": "201912345",
  "session": "2023/2024",
  "level": "500",
  "semester": "harmattan",
  "courseCodes": ["CSC 507", "CSC 511","CSC 505"]
}



###
GET {{localurl}}/advisors/get-all HTTP/1.1




### 
POST {{localurl}}/login/parent HTTP/1.1
content-type: application/json

{
    "email": "ekegrant@gmail.com",
    "password":"1234567890"
}

###
POST  {{localurl}}/login/student HTTP/1.1
content-type: application/json

{
  "email": "yo@example.com",
  "password": "password123"
}


###
GET {{localurl}}/parent/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxNzk1OTE0MCwiZXhwIjoxNzE3OTYyNzQwfQ.JWzuSHT-43sHZbb_OcjrWoVXz3Fe4Ffwe4membfSmFk

###
POST  {{localurl}}/parent/editProfile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxNjA1NDEzOSwiZXhwIjoxNzE2MDU3NzM5fQ.jN9Da7hM2DTbywbTPoEiK0mTytXISK3w-R20MxXD5ZY

{
    "firstName": "grant",
    "lastName": "eke",
    "password": "1234567890"
}
###
POST  {{localurl}}/parent/addChild HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxODM2MzA0MiwiZXhwIjoxNzE4MzY2NjQyfQ.0iPzWpQCAcKuJuJIc-dc3jjm1f4qo9T_uXqj3jYQIB0

{
    "regNo": 2019111111
}

###
POST  {{localurl}}/advisors/semesters HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ4ZTg3YjMxZTAwZDkzYWM4Y2Y3MWQiLCJlbWFpbCI6ImVrZWdyYW50QGdtYWlsLmNvbSIsImlhdCI6MTcxODM2MzA0MiwiZXhwIjoxNzE4MzY2NjQyfQ.0iPzWpQCAcKuJuJIc-dc3jjm1f4qo9T_uXqj3jYQIB0

{
    "regNo": 2019111111
}






